version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: test111
      POSTGRES_DB: crud-db
    ports:
      - "5432:5432"
  
  client:
    container_name: client
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
